# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Student-Database-Management\project\UI\delete.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Delete(object):
    def setupUi(self, Delete):
        Delete.setObjectName("Delete")
        Delete.resize(400, 141)
        self.pushButton_2 = QtWidgets.QPushButton(Delete)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 100, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(Delete)
        self.lineEdit.setGeometry(QtCore.QRect(40, 50, 341, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Delete)
        self.label.setGeometry(QtCore.QRect(30, 20, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Delete)
        self.pushButton.setGeometry(QtCore.QRect(70, 100, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Delete)
        QtCore.QMetaObject.connectSlotsByName(Delete)

    def retranslateUi(self, Delete):
        _translate = QtCore.QCoreApplication.translate
        Delete.setWindowTitle(_translate("Delete", "Delete"))
        self.pushButton_2.setText(_translate("Delete", "Close"))
        self.label.setText(_translate("Delete", "Search student ID:"))
        self.pushButton.setText(_translate("Delete", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Delete = QtWidgets.QWidget()
    ui = Ui_Delete()
    ui.setupUi(Delete)
    Delete.show()
    sys.exit(app.exec_())
