# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Student-Database-Management\project\UI\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication,QMainWindow,QTableWidgetItem,QTableWidget,QComboBox,QVBoxLayout,QGridLayout,QDialog,QWidget, \
QPushButton,QAction,QMessageBox,QLabel,QTextEdit,QProgressBar,QLineEdit, QHBoxLayout

class Ui_Signin(object):
    def setupUi(self, Signin):
        Signin.setObjectName("Signin")
        Signin.resize(279, 175)
        self.pushButton = QtWidgets.QPushButton(Signin)
        self.pushButton.setGeometry(QtCore.QRect(110, 130, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(Signin)
        self.label_3.setGeometry(QtCore.QRect(120, 20, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(Signin)
        self.frame.setGeometry(QtCore.QRect(40, 50, 201, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 10, 47, 13))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(70, 10, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 40, 47, 13))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 40, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.retranslateUi(Signin)
        QtCore.QMetaObject.connectSlotsByName(Signin)

    def retranslateUi(self, Signin):
        _translate = QtCore.QCoreApplication.translate
        Signin.setWindowTitle(_translate("Signin", "Dialog"))
        self.pushButton.setText(_translate("Signin", "Enter"))
        self.label_3.setText(_translate("Signin", "Login"))
        self.label.setText(_translate("Signin", "Username"))
        self.label_2.setText(_translate("Signin", "Password"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Signin = QtWidgets.QDialog()
    ui = Ui_Signin()
    ui.setupUi(Signin)
    Signin.show()
    sys.exit(app.exec_())
